// <auto-generated />
namespace IDEIMusic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SaleCorrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaleCorrections));
        
        string IMigrationMetadata.Id
        {
            get { return "201412051712251_SaleCorrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
